services:
  rails:
    build:
      context: .
    image: r01:1.1.0
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
      - node_modules:/rails/node_modules
    ports:
      - '3000:3000'

volumes:
  bundle:
  node_modules:
